Removed hhvm to fix composer issue
Fatal error: Uncaught exception 'InvalidArgumentException'
with message 'array_pop() expects parameter 1 by reference
in src/Composer/Util/Silencer.php:51